name: eds-notebook-targets-env
channels:
  - conda-forge
dependencies:
  - r-base=4.4.3
  - r-tidyverse
  - r-dataretrieval>=2.7.21
  - r-targets
  - r-httr2
  - r-sf
  - r-xml2
  - r-leaflet
  - r-rcolorbrewer
  - r-htmlwidgets
  - r-tigris
  - r-zip
  - r-svglite
  - r-curl>=7.0.0